# Generated by Django 4.1 on 2022-11-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('BODEGA', 'bodega'), ('FINANZAS', 'finanzas'), ('COCINA', 'cocina')], default='ADMIN', max_length=255),
        ),
    ]
