# Generated by Django 4.1 on 2022-11-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('BODEGA', 'bodega'), ('FINANZAS', 'finanzas'), ('COCINA', 'cocina')], max_length=255),
        ),
    ]
