# Generated by Django 4.1 on 2022-12-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('BODEGA', 'bodega'), ('FINANZAS', 'finanzas'), ('COCINA', 'cocina'), ('GARZON', 'garzon')], max_length=255),
        ),
    ]
