# Generated by Django 4.1 on 2022-12-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='receta',
            field=models.TextField(default=False),
        ),
    ]
