# Generated by Django 4.1 on 2022-12-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='receta',
            field=models.TextField(default=''),
        ),
    ]
