# Generated by Django 4.1 on 2022-12-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='receta',
        ),
    ]
