# Generated by Django 4.1 on 2022-12-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='receta',
            field=models.TextField(default=''),
        ),
    ]
