# Generated by Django 4.1 on 2022-11-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='medida',
            field=models.CharField(choices=[('KILOGRAMOS', 'kilogramos'), ('CAJAS', 'cajas'), ('LITROS', 'litros')], default='KILOGRAMOS', max_length=255),
        ),
    ]
