# Generated by Django 4.1 on 2022-11-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_insumos_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='medida',
            field=models.CharField(choices=[('KILOGRAMOS', 'kilogramos'), ('CAJAS', 'cajas'), ('LITROS', 'litros')], max_length=255),
        ),
    ]
